### ISSUE TITLE
Configurable headers for MailExporter

### ISSUE THREAD

**Issue by wil** [nfultz/nb2mail#8]
Hi Neal,

It would be very useful to allow the From and Subject headers to be exposed as a configuration in `MailExporter`. That way, there could be a sane defaults without having to edit the notebook metadata. Configuration parameters can also be specified on the `nbconvert` command line making it easy to override at runtime.

I have a working patch to do that. Would you be interested in a pull request?

Thanks.
Wil

**Comment by nfultz** [comment]
That would be both most excellent and very appreciated.
